### ISSUE TITLE
Fix math context for snippets

### ISSUE THREAD

**Issue by patnr** [lervag/dotvim#3]
Hi

Just wondering. Should [this](https://github.com/lervag/dotvim/blob/master/UltiSnips/tex.snippets#L3-L16) be replaced by [this](https://github.com/gillescastel/latex-snippets/blob/master/tex.snippets#L1-L12) ?

Alternatively, I found that for the new vimtex, I needed to add `['', 'Env']` to the list of `texMathZones`

Also, if I'm not mistaken, vimtex#syntax#in_mathzone (which works great) is not documented anywhere.

**Comment by lervag** [comment]
Yes, you are right. I've not noticed this myself mostly because I don't really use many snippets that rely on it.

Also, yes: the function is not documented. I am aware there is a lack of documentation for some useful functions that users may be interested in, like this one.

**Comment by lervag** [comment]
> Alternatively, I found that for the new vimtex, I needed to add ['', 'Env'] to the list of texMathZones

Not quite sure what you meant by this, but I assume it was related to the "manual" version that did not rely on `vimtex#syntax#in_mathzone`?

**Comment by patricknraanes** [comment]
Yes, that's what I meant!

**Comment by lervag** [comment]
Yes; the old version no longer works with Vimtex 2.0 due to the syntax updates, and it requires a change as you noticed. See also https://github.com/lervag/vimtex/issues/1863#issuecomment-733124368.

**Comment by lervag** [comment]
Btw, thanks for making me aware. I've added a simple documentation of the syntax function now.
